---
# tasks file for ufw
    - name: install ufw package
      apt:
            name: ufw
            state: present

    - name: Start and enable UFW
        ufw:
          state: enabled        

    - name: Allow ssh through firewall
      ufw: proto=tcp "{{ ssh_port }}"  rule=allow

    - name: Establish default incomming firewall rule
      ufw: state=enabled direction=incoming policy=deny
    
    - name: Establish default outgoing firewall rule
      ufw: state=enabled direction=outgoing policy=allow