---
  - replace: 
        path: "{{ ssh_conf_path }}"
        regexp: '#Port 22'  
        replace: "{{ ssh_port }}"

  - lineinfile:
        path: "{{ ssh_conf_path }}"
        line: 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
        insertafter: '#RekeyLimit default none'

  - lineinfile:
        path: "{{ ssh_conf_path }}"
        line: 'KexAlgorithms curve25519-sha256@libssh.org'
        insertafter: '#RekeyLimit default none'

  - lineinfile:
        path: "{{ ssh_conf_path }}"
        line: 'MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com'
        insertafter: '#RekeyLimit default none'

  - replace:
        path: "{{ ssh_conf_path }}"
        regexp: '#RekeyLimit default none'
        replace: 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'

  - replace: 
        path: "{{ ssh_conf_path }}"
        regexp: '#PasswordAuthentication yes' 
        replace: 'PasswordAuthentication no'

  - replace: 
        path: "{{ ssh_conf_path }}"
        regexp: '#ClientAliveCountMax 3' 
        replace: 'ClientAliveCountMax 2'

  - replace: 
        path: "{{ ssh_conf_path }}"
        regexp: '#ClientAliveInterval 300' 
        replace: 'ClientAliveInterval 0'

  - replace: 
        path: "{{ ssh_conf_path }}"
        regexp: 'X11Forwarding yes' 
        replace: 'X11Forwarding no'

  - replace: 
        path: "{{ ssh_conf_path }}"
        regexp: '#PubkeyAuthentication yes' 
        replace: 'PubkeyAuthentication yes'

  - replace: 
        path: "{{ ssh_conf_path }}"
        regexp: '#ChallengeResponseAuthentication no' 
        replace: 'ChallengeResponseAuthentication no'

  - replace: 
        path: "{{ ssh_conf_path }}"
        regexp: 'UsePAM yes' 
        replace: 'UsePAM no'
      
    notify: "Restart_service_ssh"     

 # - name: Establish Cronjob to update the openssh-server package on a daily basis
 #       cron:
 #         name: Cronjob to update the openssh-server package on a daily basis
 #         user: root
 #         minute: "0"
 #         hour: "0"
 #         day: "*"
 #         month: "*"
 #         weekday: "*"
 #         state: present
 #         job: "apt-get install openssh-server -y"

  - name: install unattended-upgrades package
    apt:
        name:  unattended-upgrades 
        state: present
